language: node_js
node_js:
  - "4.0"
before_install:
  - npm install -g firebase-tools
install:
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
  
# safelist
branches:
  only:
  - master